# Generated by Django 4.0.6 on 2022-08-05 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_board_credate_alter_board_writernick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 11, 21, 6, 892299)),
        ),
    ]
