# Generated by Django 4.0.2 on 2022-08-11 00:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0009_alter_board_credate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='writername',
        ),
        migrations.RemoveField(
            model_name='board',
            name='writernick',
        ),
        migrations.AddField(
            model_name='board',
            name='writerops',
            field=models.ForeignKey(db_column='writerops', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 9, 28, 45, 448035)),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(help_text='Reply ID', primary_key=True, serialize=False)),
                ('reply_comment', models.TextField(help_text='Reply Comment')),
                ('reply_id', models.ForeignKey(db_column='reply_id', on_delete=django.db.models.deletion.CASCADE, related_name='board', to='board.board')),
            ],
        ),
    ]
