# Generated by Django 4.0.2 on 2022-08-11 00:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0010_remove_board_writername_remove_board_writernick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 9, 33, 5, 12066)),
        ),
        migrations.AlterField(
            model_name='board',
            name='writerops',
            field=models.ForeignKey(db_column='writerops', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
