# Generated by Django 4.0.2 on 2022-08-11 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_alter_board_credate_alter_board_writerops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 11, 29, 4, 2743)),
        ),
    ]
