# Generated by Django 4.0.2 on 2022-08-12 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_alter_board_credate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_id',
        ),
        migrations.AddField(
            model_name='reply',
            name='comment_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 9, 59, 47, 580527)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
