# Generated by Django 4.0.2 on 2022-08-12 03:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0015_remove_reply_reply_id_reply_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_writerops',
            field=models.ForeignKey(db_column='reply_writerops', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 12, 56, 0, 202719)),
        ),
        migrations.AlterField(
            model_name='board',
            name='writerops',
            field=models.ForeignKey(db_column='writerops', on_delete=django.db.models.deletion.CASCADE, related_name='board', to=settings.AUTH_USER_MODEL),
        ),
    ]
