# Generated by Django 4.0.2 on 2022-08-12 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_reply_reply_writerops_alter_board_credate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 13, 1, 16, 748210)),
        ),
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 13, 1, 16, 748210)),
        ),
    ]
