# Generated by Django 4.0.2 on 2022-08-16 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_alter_board_credate_alter_reply_credate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 18, 45, 0, 947828)),
        ),
        migrations.AlterField(
            model_name='board',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, upload_to='low/boardpic/'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 18, 45, 0, 947828)),
        ),
    ]
