# Generated by Django 4.0.2 on 2022-08-16 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_alter_board_credate_alter_board_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 18, 59, 29, 636543)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 18, 59, 29, 636543)),
        ),
    ]
