# Generated by Django 4.0.6 on 2022-08-19 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0041_alter_board_credate_alter_reply_credate'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='boardpic/')),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 22, 43, 41, 306329)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 22, 43, 41, 306329)),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.AddField(
            model_name='file',
            name='boardops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='board.board'),
        ),
    ]
