# Generated by Django 4.0.2 on 2022-08-23 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0051_alter_board_credate_alter_reply_credate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 1, 0, 28, 987342)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 1, 0, 28, 987342)),
        ),
        migrations.CreateModel(
            name='Likey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeyboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likeyboard', to='board.board')),
                ('mainuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainuser', to='board.board')),
            ],
        ),
    ]
