# Generated by Django 4.0.6 on 2022-09-07 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0055_alter_board_credate_alter_likey_mainuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 14, 36, 29, 412345)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 14, 36, 29, 412345)),
        ),
    ]
