# Generated by Django 4.0.2 on 2022-08-11 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwm', '0025_alter_user_credate_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 9, 16, 1, 775076)),
        ),
    ]
