# Generated by Django 4.0.2 on 2022-08-20 19:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwm', '0066_alter_user_credate_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='image',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='mainuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 4, 46, 6, 939780)),
        ),
    ]
