# Generated by Django 4.0.2 on 2022-08-20 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwm', '0067_remove_subscribe_image_alter_subscribe_mainuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 4, 46, 10, 710478)),
        ),
    ]
