# Generated by Django 4.0.2 on 2022-08-23 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwm', '0070_alter_user_credate_likey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 0, 58, 7, 438341)),
        ),
        migrations.DeleteModel(
            name='Likey',
        ),
    ]
