# Generated by Django 4.0.2 on 2022-08-23 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwm', '0071_alter_user_credate_delete_likey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 1, 0, 28, 979362)),
        ),
    ]
