# Generated by Django 4.0.6 on 2022-08-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='bulltype',
            field=models.CharField(blank=True, default='7.62 x 39', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='stockfoldable',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
