# Generated by Django 4.0.6 on 2022-08-05 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_bulltype_shop_stockfoldable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='bulltype',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='stockfoldable',
        ),
    ]
