# Generated by Django 4.0.6 on 2022-08-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='credate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deldate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='usrprophoto/<built-in function id>'),
        ),
        migrations.AlterField(
            model_name='user',
            name='repcount',
            field=models.IntegerField(default=0),
        ),
    ]
