# Generated by Django 4.0.6 on 2022-08-02 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwm', '0005_alter_user_comment_alter_user_credate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 23, 24, 35, 671203)),
        ),
    ]
