# Generated by Django 4.0.6 on 2022-08-02 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwm', '0007_alter_user_comment_alter_user_credate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 4, 41, 18, 136798)),
        ),
    ]
