# Generated by Django 4.0.6 on 2022-08-02 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwm', '0009_alter_user_credate_alter_user_id_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 5, 11, 45, 181763)),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='usrprophoto/<django.db.models.fields.AutoField>'),
        ),
    ]
