# Generated by Django 4.0.6 on 2022-08-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='상품', max_length=100)),
                ('pic', models.ImageField(blank=True, upload_to='shoppic/')),
                ('comment', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
