# Generated by Django 4.0.6 on 2022-08-05 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=100)),
                ('credate', models.DateTimeField(default=datetime.datetime(2022, 8, 5, 10, 40, 29, 333251))),
                ('name', models.CharField(blank=True, default='게시글', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, upload_to='boardpic/')),
                ('comment', models.TextField(blank=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
