# Generated by Django 4.0.6 on 2022-08-05 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_credate'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='writernick',
            field=models.CharField(default='r', max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 10, 49, 24, 276223)),
        ),
    ]
