# Generated by Django 4.0.6 on 2022-08-05 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_board_writernick_alter_board_credate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='credate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 10, 50, 4, 951611)),
        ),
        migrations.AlterField(
            model_name='board',
            name='writernick',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
